application: test
version: 1
runtime: python
api_version: 1

handlers:
- url: /scripts
  static_dir: scripts

- url: /stylesheets
  static_dir: stylesheets

- url: /images
  static_dir: images

- url: /.*
  script: test.py
